version: "3.7"

services:
  chatgpt-service:
    build:
      context: .
      dockerfile: ./chatgpt-service/dockerfile
    volumes:
      - ./chatgpt-service:/chatgpt-service
      - ./:/chatgpt-service/wiki
    working_dir: /chatgpt-service
    command: ["/bin/bash", "-c", "ts-node index.ts"]
    ports:
      - '9999:9999'

  elasticsearch-service:
    image: elasticsearch:7.17.17
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

networks:
  mynetwork:


