version: "3.7"

services:
  chatgpt-service:
    build:
      context: .
      dockerfile: ./chatgpt-service/dockerfile
    volumes:
      - ./chatgpt-service:/chatgpt-service
    working_dir: /chatgpt-service
    command: ["/bin/bash", "-c", "ts-node index.ts"]

  elasticsearch-service:
    image: elasticsearch:7.17.17
  
