FROM ubuntu:22.10

RUN apt-get update
RUN apt-get install -y nodejs
RUN apt-get install -y npm
RUN apt-get install -y curl
RUN apt-get install -y wget

RUN npm install -g node@18.7.0
RUN npm install -g npm@8.18.0
RUN npm install -g ts-node@10.9.1

RUN adduser developer
USER developer
